- hosts: localhost
  become: true
  tasks:
  - name: Checkout dotfiles
    ignore_errors: True
    git:
      repo: 'https://github.com/dennisoelkers/dotfiles.git'
      dest: /home/dennis/.dotfiles
  - name: Install essential packages
    apt: 
      pkg:
      - htop
      - vim
      - zsh
      - git
      - gnupg
      - mutt
      - jq
      - fzf
      - direnv
      - autojump
      - delta
      - pass
      - peek
  - name: Add Regolith PPA
    apt_repository:
      repo: ppa:regolith-linux/release
  - name: Install basic build toolchain
    apt: name=build-essential
  - name: Installing JDK & Maven
    apt: 
      name: 
      - default-jdk-headless
      - maven
  - name: Install zoom
    apt:
      deb: https://zoom.us/client/latest/zoom_amd64.deb
  - name: Checkout NVM (node version manager)
    git:
      repo: 'https://github.com/nvm-sh/nvm'
      dest: /home/dennis/.nvm

